cd/
COLOR 4A
ECHO DELETE ALL TEMP FILES
C:
CD %TEMP%
RMDIR/S/Q %TEMP%
CD C:\WINDOWS\TEMP
RMDIR/S/Q C:\WINDOWS\TEMP
CD C:\WINDOWS\Prefetch
RMDIR/S/Q C:\WINDOWS\Prefetch
CD %TEMP%
Del/s/q *.*